source "https://rubygems.org"

# Docker image uses Ruby 3.3. Local hosts may run 3.2+.
ruby ">= 3.2.2"

gem "rails", "~> 8.0.2"
gem "pg", "~> 1.5"
gem "puma", ">= 6.4"
gem "redis", ">= 5.0"
gem "sidekiq", "~> 7.3"
gem "sidekiq-cron", "~> 2.0"
gem "bcrypt", "~> 3.1"
gem "rack-cors"
gem "bootsnap", require: false
gem "rubyzip", "~> 2.3"
gem "ruby-vips", "~> 2.2"
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
end
